<h3>Product List</h3>
<form action="/product/show" method="post" class='row'>
    <input class='form form-control col-8 m-2' type='text' name= 'search' placeholder='Enter search keyword'>
    <button type="submit" class="btn btn-primary m-2">Search</button>
</form>
<div class='row'>

    <?php
    foreach ($message as $key => $value) {
        echo "<div class=\"card m-2 col-3 bg-light\">
    <div class=\"card-body\">
    <h5 class=\"card-title card-header mb-3\"><strong>Name</strong>: $value[name]</h5>
    <h6 class=\"card-subtitle mb-2 text-muted\"><strong>Category</strong>: $value[category]</h6>
    <p class=\"card-text\"><strong>Price :</strong>$$value[price]</p>
    <a href=\"/product/edit?id=$value[_id]\" class=\"card-link card-footer mt-3\">Edit</a>
    <a href=\"/product/delete?id=$value[_id]\" class=\"card-link card-footer\">Delete</a>
    </div>
    </div>";
    }
    ?>
</div>
